/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'surface':                  '#131313',
        'surface-dim':              '#131313',
        'surface-bright':           '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low':    '#1c1b1b',
        'surface-container':        '#201f1f',
        'surface-container-high':   '#2a2a2a',
        'surface-container-highest':'#353534',
        'surface-variant':          '#353534',
        'on-surface':               '#e5e2e1',
        'on-surface-variant':       '#bbc9cf',
        'on-background':            '#e5e2e1',
        'background':               '#131313',
        'primary':                  '#a4e6ff',
        'primary-container':        '#00d1ff',
        'primary-fixed':            '#b7eaff',
        'primary-fixed-dim':        '#4cd6ff',
        'on-primary':               '#003543',
        'on-primary-container':     '#00566a',
        'on-primary-fixed':         '#001f28',
        'on-primary-fixed-variant': '#004e60',
        'inverse-primary':          '#00677f',
        'secondary':                '#9ccee2',
        'secondary-container':      '#184f60',
        'secondary-fixed':          '#b8eafe',
        'secondary-fixed-dim':      '#9ccee2',
        'on-secondary':             '#003543',
        'on-secondary-container':   '#8ec0d3',
        'on-secondary-fixed':       '#001f28',
        'on-secondary-fixed-variant':'#154d5d',
        'tertiary':                 '#ffd59c',
        'tertiary-container':       '#feb127',
        'tertiary-fixed':           '#ffddb1',
        'tertiary-fixed-dim':       '#ffba49',
        'on-tertiary':              '#442b00',
        'on-tertiary-container':    '#6b4700',
        'on-tertiary-fixed':        '#291800',
        'on-tertiary-fixed-variant':'#624000',
        'error':                    '#ffb4ab',
        'error-container':          '#93000a',
        'on-error':                 '#690005',
        'on-error-container':       '#ffdad6',
        'outline':                  '#859399',
        'outline-variant':          '#3c494e',
        'inverse-surface':          '#e5e2e1',
        'inverse-on-surface':       '#313030',
        'surface-tint':             '#4cd6ff',
      },
      fontFamily: {
        headline: ['var(--font-space-grotesk)', 'sans-serif'],
        body:     ['var(--font-inter)', 'sans-serif'],
        label:    ['var(--font-inter)', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        md:      '0.375rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        '2xl':   '0.75rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}
